export const ERROR_PASSWORD_TOO_SHORT   = "ERROR_PASSWORD_TOO_SHORT";
export const ERROR_FIELD_EMPTY          = "ERROR_FIELD_EMPTY";
export const ERROR_PASSWORD_NOT_EQUAL   = "ERROR_PASSWORD_NOT_EQUAL";
export const ERROR_EMAIL_WRONG          = "ERROR_EMAIL_WRONG";